name: Publish FitnessApp.MongoDb.Driver

on:
  push:
    branches:
    - master
    - 'feature/**'
      
jobs:  
  build:
    runs-on: ubuntu-latest    
    outputs: 
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }} 
        
    steps:
    - name: Check out Code 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 #fetch-depth is needed for GitVersion
        
    #Install and calculate the new version with GitVersion  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: 5.x
        
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      id: gitversion # step id used as reference for output values
      with:
        useConfigFile: true
        configFilePath: gitversion.yml 
      
    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Prepare package
      run: dotnet nuget add source --username voldovgan2 --password ${{ secrets.NUGET_PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/voldovgan2/index.json"
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build project 
      run: dotnet build FitnessApp.Mongo2Go.Driver.sln -c Release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore
      
    - name: Pack package
      run: dotnet pack FitnessApp.Mongo2Go.Driver/FitnessApp.Mongo2Go.Driver.csproj -o:package /p:PackageVersion='${{ steps.gitversion.outputs.SemVer }}' -c Release
           
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./package/*.nupkg --source https://nuget.pkg.github.com/voldovgan2/index.json --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }}